# Generated by Django 4.2.7 on 2024-02-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_remove_comment_likes_alter_article_likes_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Контент'),
        ),
    ]
